//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ARLang.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class ARLangParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, LOGICOP=20, RELOP=21, ADDOP=22, MULOP=23, NUMBER=24, 
		STRING=25, TYPE=26, IDENTIFIER=27, WS=28;
	public const int
		RULE_module = 0, RULE_procedure = 1, RULE_arglist = 2, RULE_arg = 3, RULE_statements = 4, 
		RULE_statement = 5, RULE_vardeclstatement = 6, RULE_printstatement = 7, 
		RULE_printlinestatement = 8, RULE_assignmentstatement = 9, RULE_callstatement = 10, 
		RULE_ifstatement = 11, RULE_whilestatement = 12, RULE_returnstatement = 13, 
		RULE_expr = 14, RULE_bexpr = 15, RULE_lexpr = 16, RULE_rexpr = 17, RULE_term = 18, 
		RULE_factor = 19, RULE_callexpr = 20, RULE_actuals = 21;
	public static readonly string[] ruleNames = {
		"module", "procedure", "arglist", "arg", "statements", "statement", "vardeclstatement", 
		"printstatement", "printlinestatement", "assignmentstatement", "callstatement", 
		"ifstatement", "whilestatement", "returnstatement", "expr", "bexpr", "lexpr", 
		"rexpr", "term", "factor", "callexpr", "actuals"
	};

	private static readonly string[] _LiteralNames = {
		null, "'FUNCTION'", "'('", "')'", "'END'", "','", "';'", "'PRINT'", "'PRINTLN'", 
		"'='", "'IF'", "'THEN'", "'ELSE'", "'ENDIF'", "'WHILE'", "'WEND'", "'RETURN'", 
		"'TRUE'", "'FALSE'", "'!'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, "LOGICOP", "RELOP", "ADDOP", 
		"MULOP", "NUMBER", "STRING", "TYPE", "IDENTIFIER", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "ARLang.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static ARLangParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public ARLangParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public ARLangParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ModuleContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(ARLangParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ProcedureContext[] procedure() {
			return GetRuleContexts<ProcedureContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ProcedureContext procedure(int i) {
			return GetRuleContext<ProcedureContext>(i);
		}
		public ModuleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_module; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterModule(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitModule(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitModule(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ModuleContext module() {
		ModuleContext _localctx = new ModuleContext(Context, State);
		EnterRule(_localctx, 0, RULE_module);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 45;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 44;
				procedure();
				}
				}
				State = 47;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==T__0 );
			State = 49;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ProcedureContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TYPE() { return GetToken(ARLangParser.TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(ARLangParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementsContext statements() {
			return GetRuleContext<StatementsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArglistContext arglist() {
			return GetRuleContext<ArglistContext>(0);
		}
		public ProcedureContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_procedure; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterProcedure(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitProcedure(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProcedure(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProcedureContext procedure() {
		ProcedureContext _localctx = new ProcedureContext(Context, State);
		EnterRule(_localctx, 2, RULE_procedure);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 51;
			Match(T__0);
			State = 52;
			Match(TYPE);
			State = 53;
			Match(IDENTIFIER);
			State = 54;
			Match(T__1);
			State = 56;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==TYPE) {
				{
				State = 55;
				arglist();
				}
			}

			State = 58;
			Match(T__2);
			State = 59;
			statements();
			State = 60;
			Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArglistContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArgContext[] arg() {
			return GetRuleContexts<ArgContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgContext arg(int i) {
			return GetRuleContext<ArgContext>(i);
		}
		public ArglistContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arglist; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterArglist(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitArglist(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArglist(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArglistContext arglist() {
		ArglistContext _localctx = new ArglistContext(Context, State);
		EnterRule(_localctx, 4, RULE_arglist);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 62;
			arg();
			State = 67;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__4) {
				{
				{
				State = 63;
				Match(T__4);
				State = 64;
				arg();
				}
				}
				State = 69;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TYPE() { return GetToken(ARLangParser.TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(ARLangParser.IDENTIFIER, 0); }
		public ArgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterArg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitArg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgContext arg() {
		ArgContext _localctx = new ArgContext(Context, State);
		EnterRule(_localctx, 6, RULE_arg);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 70;
			Match(TYPE);
			State = 71;
			Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public StatementsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statements; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterStatements(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitStatements(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatements(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementsContext statements() {
		StatementsContext _localctx = new StatementsContext(Context, State);
		EnterRule(_localctx, 8, RULE_statements);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 74;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 73;
				statement();
				}
				}
				State = 76;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 201409920L) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public VardeclstatementContext vardeclstatement() {
			return GetRuleContext<VardeclstatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PrintstatementContext printstatement() {
			return GetRuleContext<PrintstatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PrintlinestatementContext printlinestatement() {
			return GetRuleContext<PrintlinestatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentstatementContext assignmentstatement() {
			return GetRuleContext<AssignmentstatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CallstatementContext callstatement() {
			return GetRuleContext<CallstatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IfstatementContext ifstatement() {
			return GetRuleContext<IfstatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public WhilestatementContext whilestatement() {
			return GetRuleContext<WhilestatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ReturnstatementContext returnstatement() {
			return GetRuleContext<ReturnstatementContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 10, RULE_statement);
		try {
			State = 86;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 78;
				vardeclstatement();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 79;
				printstatement();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 80;
				printlinestatement();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 81;
				assignmentstatement();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 82;
				callstatement();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 83;
				ifstatement();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 84;
				whilestatement();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 85;
				returnstatement();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VardeclstatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TYPE() { return GetToken(ARLangParser.TYPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(ARLangParser.IDENTIFIER, 0); }
		public VardeclstatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_vardeclstatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterVardeclstatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitVardeclstatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVardeclstatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VardeclstatementContext vardeclstatement() {
		VardeclstatementContext _localctx = new VardeclstatementContext(Context, State);
		EnterRule(_localctx, 12, RULE_vardeclstatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 88;
			Match(TYPE);
			State = 89;
			Match(IDENTIFIER);
			State = 90;
			Match(T__5);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrintstatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public PrintstatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_printstatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterPrintstatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitPrintstatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrintstatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrintstatementContext printstatement() {
		PrintstatementContext _localctx = new PrintstatementContext(Context, State);
		EnterRule(_localctx, 14, RULE_printstatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 92;
			Match(T__6);
			State = 93;
			expr();
			State = 94;
			Match(T__5);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrintlinestatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public PrintlinestatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_printlinestatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterPrintlinestatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitPrintlinestatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrintlinestatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrintlinestatementContext printlinestatement() {
		PrintlinestatementContext _localctx = new PrintlinestatementContext(Context, State);
		EnterRule(_localctx, 16, RULE_printlinestatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 96;
			Match(T__7);
			State = 97;
			expr();
			State = 98;
			Match(T__5);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentstatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(ARLangParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public AssignmentstatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignmentstatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterAssignmentstatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitAssignmentstatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignmentstatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentstatementContext assignmentstatement() {
		AssignmentstatementContext _localctx = new AssignmentstatementContext(Context, State);
		EnterRule(_localctx, 18, RULE_assignmentstatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 100;
			Match(IDENTIFIER);
			State = 101;
			Match(T__8);
			State = 102;
			expr();
			State = 103;
			Match(T__5);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CallstatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public CallexprContext callexpr() {
			return GetRuleContext<CallexprContext>(0);
		}
		public CallstatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_callstatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterCallstatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitCallstatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCallstatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CallstatementContext callstatement() {
		CallstatementContext _localctx = new CallstatementContext(Context, State);
		EnterRule(_localctx, 20, RULE_callstatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 105;
			callexpr();
			State = 106;
			Match(T__5);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfstatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementsContext[] statements() {
			return GetRuleContexts<StatementsContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementsContext statements(int i) {
			return GetRuleContext<StatementsContext>(i);
		}
		public IfstatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ifstatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterIfstatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitIfstatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIfstatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IfstatementContext ifstatement() {
		IfstatementContext _localctx = new IfstatementContext(Context, State);
		EnterRule(_localctx, 22, RULE_ifstatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 108;
			Match(T__9);
			State = 109;
			expr();
			State = 110;
			Match(T__10);
			State = 111;
			statements();
			State = 114;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__11) {
				{
				State = 112;
				Match(T__11);
				State = 113;
				statements();
				}
			}

			State = 116;
			Match(T__12);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WhilestatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementsContext statements() {
			return GetRuleContext<StatementsContext>(0);
		}
		public WhilestatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_whilestatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterWhilestatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitWhilestatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhilestatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public WhilestatementContext whilestatement() {
		WhilestatementContext _localctx = new WhilestatementContext(Context, State);
		EnterRule(_localctx, 24, RULE_whilestatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 118;
			Match(T__13);
			State = 119;
			expr();
			State = 120;
			statements();
			State = 121;
			Match(T__14);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReturnstatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ReturnstatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_returnstatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterReturnstatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitReturnstatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReturnstatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ReturnstatementContext returnstatement() {
		ReturnstatementContext _localctx = new ReturnstatementContext(Context, State);
		EnterRule(_localctx, 26, RULE_returnstatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 123;
			Match(T__15);
			State = 124;
			expr();
			State = 125;
			Match(T__5);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public BexprContext bexpr() {
			return GetRuleContext<BexprContext>(0);
		}
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		ExprContext _localctx = new ExprContext(Context, State);
		EnterRule(_localctx, 28, RULE_expr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 127;
			bexpr();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BexprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public LexprContext[] lexpr() {
			return GetRuleContexts<LexprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public LexprContext lexpr(int i) {
			return GetRuleContext<LexprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LOGICOP() { return GetTokens(ARLangParser.LOGICOP); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LOGICOP(int i) {
			return GetToken(ARLangParser.LOGICOP, i);
		}
		public BexprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bexpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterBexpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitBexpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBexpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BexprContext bexpr() {
		BexprContext _localctx = new BexprContext(Context, State);
		EnterRule(_localctx, 30, RULE_bexpr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 129;
			lexpr();
			State = 134;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==LOGICOP) {
				{
				{
				State = 130;
				Match(LOGICOP);
				State = 131;
				lexpr();
				}
				}
				State = 136;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LexprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public RexprContext[] rexpr() {
			return GetRuleContexts<RexprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public RexprContext rexpr(int i) {
			return GetRuleContext<RexprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RELOP() { return GetToken(ARLangParser.RELOP, 0); }
		public LexprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_lexpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterLexpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitLexpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLexpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LexprContext lexpr() {
		LexprContext _localctx = new LexprContext(Context, State);
		EnterRule(_localctx, 32, RULE_lexpr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 137;
			rexpr();
			State = 140;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==RELOP) {
				{
				State = 138;
				Match(RELOP);
				State = 139;
				rexpr();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RexprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TermContext[] term() {
			return GetRuleContexts<TermContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TermContext term(int i) {
			return GetRuleContext<TermContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ADDOP() { return GetTokens(ARLangParser.ADDOP); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ADDOP(int i) {
			return GetToken(ARLangParser.ADDOP, i);
		}
		public RexprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rexpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterRexpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitRexpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRexpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RexprContext rexpr() {
		RexprContext _localctx = new RexprContext(Context, State);
		EnterRule(_localctx, 34, RULE_rexpr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 142;
			term();
			State = 147;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==ADDOP) {
				{
				{
				State = 143;
				Match(ADDOP);
				State = 144;
				term();
				}
				}
				State = 149;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TermContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FactorContext[] factor() {
			return GetRuleContexts<FactorContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FactorContext factor(int i) {
			return GetRuleContext<FactorContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] MULOP() { return GetTokens(ARLangParser.MULOP); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MULOP(int i) {
			return GetToken(ARLangParser.MULOP, i);
		}
		public TermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_term; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterTerm(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitTerm(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTerm(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TermContext term() {
		TermContext _localctx = new TermContext(Context, State);
		EnterRule(_localctx, 36, RULE_term);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 150;
			factor();
			State = 155;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==MULOP) {
				{
				{
				State = 151;
				Match(MULOP);
				State = 152;
				factor();
				}
				}
				State = 157;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FactorContext : ParserRuleContext {
		public FactorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_factor; } }
	 
		public FactorContext() { }
		public virtual void CopyFrom(FactorContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Factor_BoolTrueContext : FactorContext {
		public Factor_BoolTrueContext(FactorContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterFactor_BoolTrue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitFactor_BoolTrue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFactor_BoolTrue(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Factor_IDENTIFIERContext : FactorContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(ARLangParser.IDENTIFIER, 0); }
		public Factor_IDENTIFIERContext(FactorContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterFactor_IDENTIFIER(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitFactor_IDENTIFIER(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFactor_IDENTIFIER(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Factor_NestedExprContext : FactorContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public Factor_NestedExprContext(FactorContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterFactor_NestedExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitFactor_NestedExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFactor_NestedExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Factor_UnaryFactorContext : FactorContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ADDOP() { return GetToken(ARLangParser.ADDOP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FactorContext factor() {
			return GetRuleContext<FactorContext>(0);
		}
		public Factor_UnaryFactorContext(FactorContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterFactor_UnaryFactor(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitFactor_UnaryFactor(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFactor_UnaryFactor(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Factor_NumberContext : FactorContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(ARLangParser.NUMBER, 0); }
		public Factor_NumberContext(FactorContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterFactor_Number(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitFactor_Number(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFactor_Number(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Factor_BoolNotOperationContext : FactorContext {
		[System.Diagnostics.DebuggerNonUserCode] public FactorContext factor() {
			return GetRuleContext<FactorContext>(0);
		}
		public Factor_BoolNotOperationContext(FactorContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterFactor_BoolNotOperation(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitFactor_BoolNotOperation(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFactor_BoolNotOperation(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Factor_StringContext : FactorContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(ARLangParser.STRING, 0); }
		public Factor_StringContext(FactorContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterFactor_String(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitFactor_String(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFactor_String(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Factor_BoolFalseContext : FactorContext {
		public Factor_BoolFalseContext(FactorContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterFactor_BoolFalse(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitFactor_BoolFalse(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFactor_BoolFalse(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Factor_CallExprContext : FactorContext {
		[System.Diagnostics.DebuggerNonUserCode] public CallexprContext callexpr() {
			return GetRuleContext<CallexprContext>(0);
		}
		public Factor_CallExprContext(FactorContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterFactor_CallExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitFactor_CallExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFactor_CallExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FactorContext factor() {
		FactorContext _localctx = new FactorContext(Context, State);
		EnterRule(_localctx, 38, RULE_factor);
		try {
			State = 172;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				_localctx = new Factor_NumberContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 158;
				Match(NUMBER);
				}
				break;
			case 2:
				_localctx = new Factor_StringContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 159;
				Match(STRING);
				}
				break;
			case 3:
				_localctx = new Factor_BoolTrueContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 160;
				Match(T__16);
				}
				break;
			case 4:
				_localctx = new Factor_BoolFalseContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 161;
				Match(T__17);
				}
				break;
			case 5:
				_localctx = new Factor_IDENTIFIERContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 162;
				Match(IDENTIFIER);
				}
				break;
			case 6:
				_localctx = new Factor_NestedExprContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 163;
				Match(T__1);
				State = 164;
				expr();
				State = 165;
				Match(T__2);
				}
				break;
			case 7:
				_localctx = new Factor_UnaryFactorContext(_localctx);
				EnterOuterAlt(_localctx, 7);
				{
				State = 167;
				Match(ADDOP);
				State = 168;
				factor();
				}
				break;
			case 8:
				_localctx = new Factor_BoolNotOperationContext(_localctx);
				EnterOuterAlt(_localctx, 8);
				{
				State = 169;
				Match(T__18);
				State = 170;
				factor();
				}
				break;
			case 9:
				_localctx = new Factor_CallExprContext(_localctx);
				EnterOuterAlt(_localctx, 9);
				{
				State = 171;
				callexpr();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CallexprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(ARLangParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ActualsContext actuals() {
			return GetRuleContext<ActualsContext>(0);
		}
		public CallexprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_callexpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterCallexpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitCallexpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCallexpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CallexprContext callexpr() {
		CallexprContext _localctx = new CallexprContext(Context, State);
		EnterRule(_localctx, 40, RULE_callexpr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 174;
			Match(IDENTIFIER);
			State = 175;
			Match(T__1);
			State = 177;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 189661188L) != 0)) {
				{
				State = 176;
				actuals();
				}
			}

			State = 179;
			Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ActualsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ActualsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_actuals; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.EnterActuals(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IARLangListener typedListener = listener as IARLangListener;
			if (typedListener != null) typedListener.ExitActuals(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IARLangVisitor<TResult> typedVisitor = visitor as IARLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitActuals(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ActualsContext actuals() {
		ActualsContext _localctx = new ActualsContext(Context, State);
		EnterRule(_localctx, 42, RULE_actuals);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 181;
			expr();
			State = 186;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__4) {
				{
				{
				State = 182;
				Match(T__4);
				State = 183;
				expr();
				}
				}
				State = 188;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,28,190,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		1,0,4,0,46,8,0,11,0,12,0,47,1,0,1,0,1,1,1,1,1,1,1,1,1,1,3,1,57,8,1,1,1,
		1,1,1,1,1,1,1,2,1,2,1,2,5,2,66,8,2,10,2,12,2,69,9,2,1,3,1,3,1,3,1,4,4,
		4,75,8,4,11,4,12,4,76,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,3,5,87,8,5,1,6,1,
		6,1,6,1,6,1,7,1,7,1,7,1,7,1,8,1,8,1,8,1,8,1,9,1,9,1,9,1,9,1,9,1,10,1,10,
		1,10,1,11,1,11,1,11,1,11,1,11,1,11,3,11,115,8,11,1,11,1,11,1,12,1,12,1,
		12,1,12,1,12,1,13,1,13,1,13,1,13,1,14,1,14,1,15,1,15,1,15,5,15,133,8,15,
		10,15,12,15,136,9,15,1,16,1,16,1,16,3,16,141,8,16,1,17,1,17,1,17,5,17,
		146,8,17,10,17,12,17,149,9,17,1,18,1,18,1,18,5,18,154,8,18,10,18,12,18,
		157,9,18,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,
		19,1,19,3,19,173,8,19,1,20,1,20,1,20,3,20,178,8,20,1,20,1,20,1,21,1,21,
		1,21,5,21,185,8,21,10,21,12,21,188,9,21,1,21,0,0,22,0,2,4,6,8,10,12,14,
		16,18,20,22,24,26,28,30,32,34,36,38,40,42,0,0,193,0,45,1,0,0,0,2,51,1,
		0,0,0,4,62,1,0,0,0,6,70,1,0,0,0,8,74,1,0,0,0,10,86,1,0,0,0,12,88,1,0,0,
		0,14,92,1,0,0,0,16,96,1,0,0,0,18,100,1,0,0,0,20,105,1,0,0,0,22,108,1,0,
		0,0,24,118,1,0,0,0,26,123,1,0,0,0,28,127,1,0,0,0,30,129,1,0,0,0,32,137,
		1,0,0,0,34,142,1,0,0,0,36,150,1,0,0,0,38,172,1,0,0,0,40,174,1,0,0,0,42,
		181,1,0,0,0,44,46,3,2,1,0,45,44,1,0,0,0,46,47,1,0,0,0,47,45,1,0,0,0,47,
		48,1,0,0,0,48,49,1,0,0,0,49,50,5,0,0,1,50,1,1,0,0,0,51,52,5,1,0,0,52,53,
		5,26,0,0,53,54,5,27,0,0,54,56,5,2,0,0,55,57,3,4,2,0,56,55,1,0,0,0,56,57,
		1,0,0,0,57,58,1,0,0,0,58,59,5,3,0,0,59,60,3,8,4,0,60,61,5,4,0,0,61,3,1,
		0,0,0,62,67,3,6,3,0,63,64,5,5,0,0,64,66,3,6,3,0,65,63,1,0,0,0,66,69,1,
		0,0,0,67,65,1,0,0,0,67,68,1,0,0,0,68,5,1,0,0,0,69,67,1,0,0,0,70,71,5,26,
		0,0,71,72,5,27,0,0,72,7,1,0,0,0,73,75,3,10,5,0,74,73,1,0,0,0,75,76,1,0,
		0,0,76,74,1,0,0,0,76,77,1,0,0,0,77,9,1,0,0,0,78,87,3,12,6,0,79,87,3,14,
		7,0,80,87,3,16,8,0,81,87,3,18,9,0,82,87,3,20,10,0,83,87,3,22,11,0,84,87,
		3,24,12,0,85,87,3,26,13,0,86,78,1,0,0,0,86,79,1,0,0,0,86,80,1,0,0,0,86,
		81,1,0,0,0,86,82,1,0,0,0,86,83,1,0,0,0,86,84,1,0,0,0,86,85,1,0,0,0,87,
		11,1,0,0,0,88,89,5,26,0,0,89,90,5,27,0,0,90,91,5,6,0,0,91,13,1,0,0,0,92,
		93,5,7,0,0,93,94,3,28,14,0,94,95,5,6,0,0,95,15,1,0,0,0,96,97,5,8,0,0,97,
		98,3,28,14,0,98,99,5,6,0,0,99,17,1,0,0,0,100,101,5,27,0,0,101,102,5,9,
		0,0,102,103,3,28,14,0,103,104,5,6,0,0,104,19,1,0,0,0,105,106,3,40,20,0,
		106,107,5,6,0,0,107,21,1,0,0,0,108,109,5,10,0,0,109,110,3,28,14,0,110,
		111,5,11,0,0,111,114,3,8,4,0,112,113,5,12,0,0,113,115,3,8,4,0,114,112,
		1,0,0,0,114,115,1,0,0,0,115,116,1,0,0,0,116,117,5,13,0,0,117,23,1,0,0,
		0,118,119,5,14,0,0,119,120,3,28,14,0,120,121,3,8,4,0,121,122,5,15,0,0,
		122,25,1,0,0,0,123,124,5,16,0,0,124,125,3,28,14,0,125,126,5,6,0,0,126,
		27,1,0,0,0,127,128,3,30,15,0,128,29,1,0,0,0,129,134,3,32,16,0,130,131,
		5,20,0,0,131,133,3,32,16,0,132,130,1,0,0,0,133,136,1,0,0,0,134,132,1,0,
		0,0,134,135,1,0,0,0,135,31,1,0,0,0,136,134,1,0,0,0,137,140,3,34,17,0,138,
		139,5,21,0,0,139,141,3,34,17,0,140,138,1,0,0,0,140,141,1,0,0,0,141,33,
		1,0,0,0,142,147,3,36,18,0,143,144,5,22,0,0,144,146,3,36,18,0,145,143,1,
		0,0,0,146,149,1,0,0,0,147,145,1,0,0,0,147,148,1,0,0,0,148,35,1,0,0,0,149,
		147,1,0,0,0,150,155,3,38,19,0,151,152,5,23,0,0,152,154,3,38,19,0,153,151,
		1,0,0,0,154,157,1,0,0,0,155,153,1,0,0,0,155,156,1,0,0,0,156,37,1,0,0,0,
		157,155,1,0,0,0,158,173,5,24,0,0,159,173,5,25,0,0,160,173,5,17,0,0,161,
		173,5,18,0,0,162,173,5,27,0,0,163,164,5,2,0,0,164,165,3,28,14,0,165,166,
		5,3,0,0,166,173,1,0,0,0,167,168,5,22,0,0,168,173,3,38,19,0,169,170,5,19,
		0,0,170,173,3,38,19,0,171,173,3,40,20,0,172,158,1,0,0,0,172,159,1,0,0,
		0,172,160,1,0,0,0,172,161,1,0,0,0,172,162,1,0,0,0,172,163,1,0,0,0,172,
		167,1,0,0,0,172,169,1,0,0,0,172,171,1,0,0,0,173,39,1,0,0,0,174,175,5,27,
		0,0,175,177,5,2,0,0,176,178,3,42,21,0,177,176,1,0,0,0,177,178,1,0,0,0,
		178,179,1,0,0,0,179,180,5,3,0,0,180,41,1,0,0,0,181,186,3,28,14,0,182,183,
		5,5,0,0,183,185,3,28,14,0,184,182,1,0,0,0,185,188,1,0,0,0,186,184,1,0,
		0,0,186,187,1,0,0,0,187,43,1,0,0,0,188,186,1,0,0,0,13,47,56,67,76,86,114,
		134,140,147,155,172,177,186
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
