//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ARLang.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IARLangListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ARLangBaseListener : IARLangListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.module"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModule([NotNull] ARLangParser.ModuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.module"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModule([NotNull] ARLangParser.ModuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.procedure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedure([NotNull] ARLangParser.ProcedureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.procedure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedure([NotNull] ARLangParser.ProcedureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.arglist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArglist([NotNull] ARLangParser.ArglistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.arglist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArglist([NotNull] ARLangParser.ArglistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArg([NotNull] ARLangParser.ArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArg([NotNull] ARLangParser.ArgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.statements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatements([NotNull] ARLangParser.StatementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.statements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatements([NotNull] ARLangParser.StatementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] ARLangParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] ARLangParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.vardeclstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVardeclstatement([NotNull] ARLangParser.VardeclstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.vardeclstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVardeclstatement([NotNull] ARLangParser.VardeclstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.printstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintstatement([NotNull] ARLangParser.PrintstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.printstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintstatement([NotNull] ARLangParser.PrintstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.printlinestatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrintlinestatement([NotNull] ARLangParser.PrintlinestatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.printlinestatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrintlinestatement([NotNull] ARLangParser.PrintlinestatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.assignmentstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentstatement([NotNull] ARLangParser.AssignmentstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.assignmentstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentstatement([NotNull] ARLangParser.AssignmentstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.callstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallstatement([NotNull] ARLangParser.CallstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.callstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallstatement([NotNull] ARLangParser.CallstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.ifstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfstatement([NotNull] ARLangParser.IfstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.ifstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfstatement([NotNull] ARLangParser.IfstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.whilestatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhilestatement([NotNull] ARLangParser.WhilestatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.whilestatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhilestatement([NotNull] ARLangParser.WhilestatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.returnstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnstatement([NotNull] ARLangParser.ReturnstatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.returnstatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnstatement([NotNull] ARLangParser.ReturnstatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] ARLangParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] ARLangParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.bexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBexpr([NotNull] ARLangParser.BexprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.bexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBexpr([NotNull] ARLangParser.BexprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.lexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLexpr([NotNull] ARLangParser.LexprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.lexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLexpr([NotNull] ARLangParser.LexprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.rexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRexpr([NotNull] ARLangParser.RexprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.rexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRexpr([NotNull] ARLangParser.RexprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] ARLangParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] ARLangParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>factor_Number</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor_Number([NotNull] ARLangParser.Factor_NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>factor_Number</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor_Number([NotNull] ARLangParser.Factor_NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>factor_String</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor_String([NotNull] ARLangParser.Factor_StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>factor_String</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor_String([NotNull] ARLangParser.Factor_StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>factor_BoolTrue</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor_BoolTrue([NotNull] ARLangParser.Factor_BoolTrueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>factor_BoolTrue</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor_BoolTrue([NotNull] ARLangParser.Factor_BoolTrueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>factor_BoolFalse</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor_BoolFalse([NotNull] ARLangParser.Factor_BoolFalseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>factor_BoolFalse</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor_BoolFalse([NotNull] ARLangParser.Factor_BoolFalseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>factor_IDENTIFIER</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor_IDENTIFIER([NotNull] ARLangParser.Factor_IDENTIFIERContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>factor_IDENTIFIER</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor_IDENTIFIER([NotNull] ARLangParser.Factor_IDENTIFIERContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>factor_NestedExpr</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor_NestedExpr([NotNull] ARLangParser.Factor_NestedExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>factor_NestedExpr</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor_NestedExpr([NotNull] ARLangParser.Factor_NestedExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>factor_UnaryFactor</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor_UnaryFactor([NotNull] ARLangParser.Factor_UnaryFactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>factor_UnaryFactor</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor_UnaryFactor([NotNull] ARLangParser.Factor_UnaryFactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>factor_BoolNotOperation</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor_BoolNotOperation([NotNull] ARLangParser.Factor_BoolNotOperationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>factor_BoolNotOperation</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor_BoolNotOperation([NotNull] ARLangParser.Factor_BoolNotOperationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>factor_CallExpr</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor_CallExpr([NotNull] ARLangParser.Factor_CallExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>factor_CallExpr</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor_CallExpr([NotNull] ARLangParser.Factor_CallExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.callexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallexpr([NotNull] ARLangParser.CallexprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.callexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallexpr([NotNull] ARLangParser.CallexprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.actuals"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActuals([NotNull] ARLangParser.ActualsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.actuals"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActuals([NotNull] ARLangParser.ActualsContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
