//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ARLang.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ARLangParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IARLangVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule([NotNull] ARLangParser.ModuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.procedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedure([NotNull] ARLangParser.ProcedureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.arglist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArglist([NotNull] ARLangParser.ArglistContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArg([NotNull] ARLangParser.ArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatements([NotNull] ARLangParser.StatementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] ARLangParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.vardeclstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVardeclstatement([NotNull] ARLangParser.VardeclstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.printstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintstatement([NotNull] ARLangParser.PrintstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.printlinestatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintlinestatement([NotNull] ARLangParser.PrintlinestatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.assignmentstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentstatement([NotNull] ARLangParser.AssignmentstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.callstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallstatement([NotNull] ARLangParser.CallstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.ifstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfstatement([NotNull] ARLangParser.IfstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.whilestatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhilestatement([NotNull] ARLangParser.WhilestatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.returnstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnstatement([NotNull] ARLangParser.ReturnstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] ARLangParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.bexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBexpr([NotNull] ARLangParser.BexprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.lexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLexpr([NotNull] ARLangParser.LexprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.rexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRexpr([NotNull] ARLangParser.RexprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] ARLangParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>factor_Number</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor_Number([NotNull] ARLangParser.Factor_NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>factor_String</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor_String([NotNull] ARLangParser.Factor_StringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>factor_BoolTrue</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor_BoolTrue([NotNull] ARLangParser.Factor_BoolTrueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>factor_BoolFalse</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor_BoolFalse([NotNull] ARLangParser.Factor_BoolFalseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>factor_IDENTIFIER</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor_IDENTIFIER([NotNull] ARLangParser.Factor_IDENTIFIERContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>factor_NestedExpr</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor_NestedExpr([NotNull] ARLangParser.Factor_NestedExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>factor_UnaryFactor</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor_UnaryFactor([NotNull] ARLangParser.Factor_UnaryFactorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>factor_BoolNotOperation</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor_BoolNotOperation([NotNull] ARLangParser.Factor_BoolNotOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>factor_CallExpr</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor_CallExpr([NotNull] ARLangParser.Factor_CallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.callexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallexpr([NotNull] ARLangParser.CallexprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ARLangParser.actuals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActuals([NotNull] ARLangParser.ActualsContext context);
}
