//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ARLang.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ARLangParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IARLangListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModule([NotNull] ARLangParser.ModuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModule([NotNull] ARLangParser.ModuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.procedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedure([NotNull] ARLangParser.ProcedureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.procedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedure([NotNull] ARLangParser.ProcedureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.arglist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArglist([NotNull] ARLangParser.ArglistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.arglist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArglist([NotNull] ARLangParser.ArglistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArg([NotNull] ARLangParser.ArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArg([NotNull] ARLangParser.ArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatements([NotNull] ARLangParser.StatementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatements([NotNull] ARLangParser.StatementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] ARLangParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] ARLangParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.vardeclstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVardeclstatement([NotNull] ARLangParser.VardeclstatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.vardeclstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVardeclstatement([NotNull] ARLangParser.VardeclstatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.printstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintstatement([NotNull] ARLangParser.PrintstatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.printstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintstatement([NotNull] ARLangParser.PrintstatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.printlinestatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintlinestatement([NotNull] ARLangParser.PrintlinestatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.printlinestatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintlinestatement([NotNull] ARLangParser.PrintlinestatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.assignmentstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentstatement([NotNull] ARLangParser.AssignmentstatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.assignmentstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentstatement([NotNull] ARLangParser.AssignmentstatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.callstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallstatement([NotNull] ARLangParser.CallstatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.callstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallstatement([NotNull] ARLangParser.CallstatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.ifstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfstatement([NotNull] ARLangParser.IfstatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.ifstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfstatement([NotNull] ARLangParser.IfstatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.whilestatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhilestatement([NotNull] ARLangParser.WhilestatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.whilestatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhilestatement([NotNull] ARLangParser.WhilestatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.returnstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnstatement([NotNull] ARLangParser.ReturnstatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.returnstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnstatement([NotNull] ARLangParser.ReturnstatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] ARLangParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] ARLangParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.bexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBexpr([NotNull] ARLangParser.BexprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.bexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBexpr([NotNull] ARLangParser.BexprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.lexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLexpr([NotNull] ARLangParser.LexprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.lexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLexpr([NotNull] ARLangParser.LexprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.rexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRexpr([NotNull] ARLangParser.RexprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.rexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRexpr([NotNull] ARLangParser.RexprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] ARLangParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] ARLangParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>factor_Number</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor_Number([NotNull] ARLangParser.Factor_NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>factor_Number</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor_Number([NotNull] ARLangParser.Factor_NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>factor_String</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor_String([NotNull] ARLangParser.Factor_StringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>factor_String</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor_String([NotNull] ARLangParser.Factor_StringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>factor_BoolTrue</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor_BoolTrue([NotNull] ARLangParser.Factor_BoolTrueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>factor_BoolTrue</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor_BoolTrue([NotNull] ARLangParser.Factor_BoolTrueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>factor_BoolFalse</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor_BoolFalse([NotNull] ARLangParser.Factor_BoolFalseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>factor_BoolFalse</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor_BoolFalse([NotNull] ARLangParser.Factor_BoolFalseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>factor_IDENTIFIER</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor_IDENTIFIER([NotNull] ARLangParser.Factor_IDENTIFIERContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>factor_IDENTIFIER</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor_IDENTIFIER([NotNull] ARLangParser.Factor_IDENTIFIERContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>factor_NestedExpr</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor_NestedExpr([NotNull] ARLangParser.Factor_NestedExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>factor_NestedExpr</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor_NestedExpr([NotNull] ARLangParser.Factor_NestedExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>factor_UnaryFactor</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor_UnaryFactor([NotNull] ARLangParser.Factor_UnaryFactorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>factor_UnaryFactor</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor_UnaryFactor([NotNull] ARLangParser.Factor_UnaryFactorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>factor_BoolNotOperation</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor_BoolNotOperation([NotNull] ARLangParser.Factor_BoolNotOperationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>factor_BoolNotOperation</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor_BoolNotOperation([NotNull] ARLangParser.Factor_BoolNotOperationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>factor_CallExpr</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor_CallExpr([NotNull] ARLangParser.Factor_CallExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>factor_CallExpr</c>
	/// labeled alternative in <see cref="ARLangParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor_CallExpr([NotNull] ARLangParser.Factor_CallExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.callexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallexpr([NotNull] ARLangParser.CallexprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.callexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallexpr([NotNull] ARLangParser.CallexprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ARLangParser.actuals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActuals([NotNull] ARLangParser.ActualsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ARLangParser.actuals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActuals([NotNull] ARLangParser.ActualsContext context);
}
